### ISSUE TITLE
problem with app.py

### ISSUE THREAD

**Issue by belidi** [KitronikLtd/Kitronik-Raspberry-Pi-Air-Quality-Control-HAT-Dashboard-Python#1]
When I run app.py I get this error: Traceback (most recent call last):
   File "/home/pi/Kitronik-Raspberry-Pi-Air-Quality-Control-HAT-Dashboard-Python/app.py", line 286, in <module>
     hpo1.changeDutyCycle(int(hpo_data[1]))
ValueError: invalid literal for int() with base 10: 'Off'

**Comment by JackAtKitronik** [comment]
Hi @belidi,

Thanks for letting us know. We have fixed the issue in the lastest commit here: ad30526353231d57ba8265ee31f8d2bf533300d5

It was simply an issue with the default High Power Out values. When there are no values in the database we have to pass default values to setup the home page, and these values were in the wrong format.
